from environs import Env

env = Env()
env.read_env()

BOT_TOKEN = env.str('BOT_TOKEN')

PLAY_CHAT_ID = env.int('PLAY_CHAT_ID')
FIND_CHAT_ID = env.int('FIND_CHAT_ID')

TIME_GAME_LIVE = env.int('TIME_GAME_LIVE')
TIME_INVOICE_LIVE = env.int('TIME_INVOICE_LIVE')

ADMIN_IDS = [6258421903, 5422832796, 2134081408]

DICE_PHOTO = "AgACAgIAAxkBAAIE_WYD93lxjiIBHMxqqLg5BrtUQD7-AALr2DEbvsQgSIGAEQ4hLFkJAQADAgADeQADNAQ"
DARTS_PHOTO = "AgACAgIAAxkBAAIE_2YD955GlbpkRXR6ZnDbcdIYgwf0AALs2DEbvsQgSGkcc4r_iezHAQADAgADeQADNAQ"
BOWLING_PHOTO = "AgACAgIAAxkBAAIE_GYD91wpGaYGPjtTiDEXiCcxjOkvAALo2DEbvsQgSLUwSHtxR-KdAQADAgADeQADNAQ"
